# Loads default set of integrations. Do not remove.
default_config:

logger:
  default: warning
  logs:
    custom_components.go_echarger: debug

# config:
#   - hacs.disable(HacsDisabledReason.RATE_LIMIT) return True
