# Loads default set of integrations. Do not remove.
default_config:

logger:
  default: warning
  logs:
    custom_components.go_echarger: debug
    custom_components.hacs: debug
    aiogithubapi: debug

sensor:
  - platform: time_date
    display_options:
      - 'date_time'

# uncomment if you want to have a quick access without HACS
# go_echarger:
