# Loads default set of integrations. Do not remove.
default_config:

logger:
  default: warning
  logs:
    custom_components.go_echarger: debug
    custom_components.hacs: debug
    aiogithubapi: debug

sensor:
  - platform: time_date
    display_options:
      - 'date_time'

# uncomment if you want to have a quick access/test without HACS
# change mock values to the real values
# go_echarger:
#   chargers:
#     - name: charger1
#       host: http://mock-api:4000
#       api_token: TEST
