# Loads default set of integrations. Do not remove.
default_config:

logger:
  default: warning
  logs:
    custom_components.go_echarger: debug
    custom_components.hacs: debug
    aiogithubapi: debug

sensor:
  - platform: time_date
    display_options:
      - 'date_time'

go_echarger:
  chargers:
    - name: charger1
      host: http://localhost:4000
      api_token: TEST
